create table ARTICLES (id bigint not null auto_increment, content varchar(255), created_at datetime(6), title varchar(50), updated_at datetime(6), author_id bigint, theme_id bigint, primary key (id)) engine=InnoDB;
create table COMMENTS (id bigint not null auto_increment, content varchar(255), created_at datetime(6), updated_at datetime(6), article_id bigint, author_id bigint, primary key (id)) engine=InnoDB;
create table SUBSCRIPTIONS (id bigint not null auto_increment, created_at datetime(6), updated_at datetime(6), theme_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table THEMES (id bigint not null auto_increment, created_at datetime(6), name varchar(200), updated_at datetime(6), primary key (id)) engine=InnoDB;
alter table USERS add column username varchar(20);
alter table ARTICLES add constraint FKjnt23nr1d7wt0sjl2dof5mip5 foreign key (author_id) references USERS (id);
alter table ARTICLES add constraint FKb26fanb9ju1i0ym1gswhj0cg6 foreign key (theme_id) references THEMES (id);
alter table COMMENTS add constraint FKf64h7ce877ohr18431t5oqcit foreign key (article_id) references ARTICLES (id);
alter table COMMENTS add constraint FKbr9p7rllqhrjo97rucg45lhfx foreign key (author_id) references USERS (id);
alter table SUBSCRIPTIONS add constraint FKpn4yxeolhg898i28a1p5tvti2 foreign key (theme_id) references THEMES (id);
alter table SUBSCRIPTIONS add constraint FKgb4j0qpwv6hdgy7aotoobd4ty foreign key (user_id) references USERS (id);
